### ISSUE TITLE
병목

### ISSUE THREAD

**Issue by 2DU** [2DU/NamuJSON-openNAMU-Python#1]
이 물건으로 나무위키 json을 오픈나무 형식으로 변경해서 저장하고 오픈나무를 키면 엄청난 병목 생김

그래서 파이썬 문제인가하고 확인 했는데 아닌듯 Node.js로도 타카미 치카 항목 찾는 데만 40초 걸림

아무래도 db 방법의 새로운 최적화가 필요해보임

ps. 왜 이슈를 안 열었을까?

**Comment by g3nlish** [comment]
참고로 json에서 오픈나무로 옮기는 중에 DB렉 개오짐

**Comment by g3nlish** [comment]
그리고 json에서 오픈나무로 옮기고 나면 DB 가 맛가는듯한 DB 새로고침을 하면 행을 다 불러오지를 못함.

**Comment by 2DU** [comment]
적혀 있듯이 램을 8기가나 냠냠해서 그렇습니다.

후에 그냥 SQL 파일로 올리겠습니다

**Comment by 2DU** [comment]
또 DB 용량이 겁나 커서 DB 자체에서도 버벅 거림과 병목 현상이...

**Comment by g3nlish** [comment]
http://imgur.com/eNWBBMO
http://imgur.com/L9TxBOK
이제 60만줄로 넘어가는 과정인데 언제 끝나는지도 모르겠고 F5 누를때마다 데이터 행을 제대로 불여들이지 못하는 부분이 쪼매 그렇네요. 근데 이걸 sql로 덤프시켜서 다시 복원시키면 멀쩡해질것 같은 기분이?

**Comment by g3nlish** [comment]
http://imgur.com/6xaEKVl
그렇게 들어갈수가 없답니다....

**Comment by 2DU** [comment]
어서오세요 mysql의 병목에 오신 것을 환영합니다

여기서부터는 이 프로그램의 병목의 세계가 아닙니다

**Comment by g3nlish** [comment]
와아아아아아아아아아아

**Comment by 2DU** [comment]
이 문제를 후에 좀 다른 방식으로 처리해야 겠습니다

**Comment by 2DU** [comment]
일단 닫아야 겠다
